---
# vars file for nginx-wordpress
software:
  - nginx
  - php
  - php-mysql
  - php-fpm
  - php-curl
  - php-gd
  - php-intl
  - php-mbstring
  - php-soap
  - php-xml
  - php-xmlrpc
  - php-zip

